packages:
  - "packages/*"
  - "services/*"
  - "apps/*"

allowBuilds:
  esbuild: set this to true or false

overrides:
  drizzle-orm: "^0.45.2"
  lodash-es: "^4.17.24"
  qs: "^6.16.0"
  esbuild: "^0.25.0"
