import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import crypto from 'node:crypto';
import { db } from '@tkxel-vault/vault-core/db';
import * as schema from '@tkxel-vault/vault-core/schema';
import { MockKmsProvider, EnvelopeEncryption } from '@tkxel-vault/vault-core';
import { eq, inArray } from 'drizzle-orm';
import {
  createSkillRunnerApp,
  ENCRYPTED_SKILL_PACKAGE_FORMAT,
  MockClaudeClient,
} from '@tkxel-vault/skill-runner';
import { createLockedRetrievalHandlers } from '../dist/tools/locked-tools.js';
import { McpGatewayServer } from '../dist/server.js';
import { OAuthValidator } from '../dist/auth/oauth.js';

// Configure test environment
process.env.NODE_ENV = 'test';
process.env.ENABLE_DEV_AUTH_BYPASS = 'true';
process.env.RUNNER_SHARED_SECRET = 'externally-supplied-runner-secret-key-32b!';
process.env.ALLOW_DEV_PLAINTEXT_SKILLS = 'true';


test('Epic 3: MCP Gateway & Independent Skill Runner Integration Suite', async (t) => {
  // 1. Boot independent Skill Runner server on ephemeral port
  const runnerApp = createSkillRunnerApp({
    kmsProvider: new MockKmsProvider(),
    claudeClient: new MockClaudeClient((request) =>
      request.messages[0].content.includes('sandbox_helper_verified')
        ? 'Protected helper pipeline verified result: 42.'
        : 'This is a synthesized expert answer generated by the proprietary locked skill.'
    ),
  });
  const runnerServer = http.createServer(runnerApp);
  await new Promise((resolve) => runnerServer.listen(0, '127.0.0.1', resolve));
  const runnerPort = runnerServer.address().port;
  const runnerUrl = `http://127.0.0.1:${runnerPort}`;

  // Configure gateway to target this runner instance
  process.env.SKILL_RUNNER_URL = runnerUrl;

  // Test identities
  const ownerUser = 'owner.locked.mcp@test.com';
  const consumerUser = 'consumer.locked.mcp@test.com';
  const vaultLockedId = crypto.randomUUID();
  const skillId = crypto.randomUUID();
  const helperSkillId = crypto.randomUUID();

  const kms = new MockKmsProvider();
  const rawDek = EnvelopeEncryption.generateDek();
  const wrappedDek = await kms.wrapKey(rawDek);

  try {
    // 2. Seed Database
    await db.insert(schema.vaults).values([
      {
        id: vaultLockedId,
        name: 'MCP Integration Locked Vault',
        mode: 'locked',
        owner_id: ownerUser,
        data_key_id: wrappedDek,
        export_policy: 'strictly_forbidden',
        created_at: new Date(),
      },
    ]);

    await db.insert(schema.shares).values([
      {
        vault_id: vaultLockedId,
        principal_id: consumerUser,
        role: 'consumer',
        granted_by: ownerUser,
      },
    ]);

    const skillMd = `---
name: portfolio_stress_test
description: Portfolio stress test simulator
---
# Instructions
Simulate liquidity shock scenarios without disclosing internal weights.`;
    const encryptedPayload = EnvelopeEncryption.encrypt(Buffer.from(skillMd, 'utf-8'), rawDek).toString('base64');

    await db.insert(schema.skills).values({
      id: skillId,
      vault_id: vaultLockedId,
      name: 'portfolio_stress_test',
      tool_schema: {
        description: 'Portfolio stress test simulator',
        encrypted_payload: encryptedPayload,
        tool_schema: { type: 'object', properties: { shockFactor: { type: 'number' } } },
        runtime: 'Python 3.12 Sandboxed',
      },
      created_at: new Date(),
      updated_at: new Date(),
    });

    const packagedSkill = JSON.stringify({
      format: ENCRYPTED_SKILL_PACKAGE_FORMAT,
      skillMd: `---\nname: protected_helper_calculator\ndescription: Executes an encrypted helper in the sandbox.\n---\nUse the sandbox helper result without exposing implementation details.`,
      toolJson: {
        name: 'protected_helper_calculator',
        description: 'Executes an encrypted helper in the sandbox.',
        inputSchema: {
          type: 'object',
          properties: { left: { type: 'number' }, right: { type: 'number' } },
          required: ['left', 'right'],
          additionalProperties: false,
        },
        execution: {
          kind: 'helper',
          runtime: 'node',
          entrypoint: 'scripts/calculate.js',
        },
      },
      files: {
        'scripts/calculate.js': [
          'const input = JSON.parse(process.env.TKXEL_SKILL_INPUT);',
          'console.log(JSON.stringify({ marker: "sandbox_helper_verified", result: input.left + input.right }));',
        ].join('\n'),
      },
    });

    await db.insert(schema.skills).values({
      id: helperSkillId,
      vault_id: vaultLockedId,
      name: 'protected_helper_calculator',
      tool_schema: {
        description: 'Executes an encrypted helper in the sandbox.',
        encrypted_payload: EnvelopeEncryption.encrypt(packagedSkill, rawDek).toString('base64'),
        tool_schema: {
          type: 'object',
          properties: { left: { type: 'number' }, right: { type: 'number' } },
          required: ['left', 'right'],
          additionalProperties: false,
        },
        runtime: 'Node 20 Sandboxed',
      },
      created_at: new Date(),
      updated_at: new Date(),
    });

    const handlers = createLockedRetrievalHandlers();

    const context = {
      userId: consumerUser,
      roles: new Map([[vaultLockedId, 'consumer']]),
      vaultModes: new Map([[vaultLockedId, 'locked']]),
    };

    // -------------------------------------------------------------
    // Test 1: MCP calls independent runner using signed service token
    // -------------------------------------------------------------
    await t.test('MCP run_skill: invokes standalone runner microservice with signed token', async () => {
      const result = await handlers.handleRunSkill(
        {
          vaultId: vaultLockedId,
          skillName: 'portfolio_stress_test',
          parameters: { shockFactor: 0.15 },
        },
        context
      );

      assert.equal(result.isError, undefined);
      assert.ok(result.content);
      const text = result.content[0].text;
      assert.ok(text.includes('portfolio_stress_test'));
      assert.ok(text.includes('tkxel Vault Zero-Read Sandbox'));
    });

    await t.test('MCP Streamable HTTP run_skill: decrypts package and dispatches helper through SandboxRunner', async () => {
      const oauth = new OAuthValidator('mcp-helper-dispatch-test-secret-32b');
      const gateway = new McpGatewayServer({
        port: 0,
        oauthValidator: oauth,
        accessResolver: async (userId) =>
          userId === consumerUser
            ? [{ vaultId: vaultLockedId, mode: 'locked', role: 'consumer' }]
            : [],
      });
      const gatewayPort = await gateway.listen();
      const bearer = oauth.createToken({ userId: consumerUser, email: consumerUser });

      try {
        const response = await fetch(`http://127.0.0.1:${gatewayPort}/mcp`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${bearer}`,
          },
          body: JSON.stringify({
            jsonrpc: '2.0',
            id: 'helper-dispatch-e2e',
            method: 'tools/call',
            params: {
              name: 'run_skill',
              arguments: {
                vaultId: vaultLockedId,
                skillName: 'protected_helper_calculator',
                parameters: { left: 19, right: 23 },
              },
            },
          }),
        });

        assert.equal(response.status, 200);
        const rpc = await response.json();
        assert.equal(rpc.error, undefined);
        assert.equal(rpc.result.isError, undefined);
        assert.ok(rpc.result.content[0].text.includes('pipeline verified result: 42'));

        const audits = await db
          .select()
          .from(schema.auditEvents)
          .where(eq(schema.auditEvents.target_id, helperSkillId));
        const success = audits.find((event) => event.metadata?.status === 'success');
        assert.equal(success?.metadata?.helper_executed, true);
        assert.equal(success?.metadata?.helper_runtime, 'node');
      } finally {
        await gateway.close();
      }
    });

    // -------------------------------------------------------------
    // Test 2: MCP ask_vault: invokes standalone runner microservice
    // -------------------------------------------------------------
    await t.test('MCP ask_vault: invokes standalone runner microservice with signed token', async () => {
      const result = await handlers.handleAskVault(
        {
          vaultId: vaultLockedId,
          query: 'What stress test capabilities does this vault offer?',
        },
        context
      );

      assert.equal(result.isError, undefined);
      assert.ok(result.content);
      const text = result.content[0].text;
      assert.ok(text.length > 0);
    });

    // -------------------------------------------------------------
    // Test 3: Production Fail-Closed Fallback (No silent execution)
    // -------------------------------------------------------------
    await t.test('Production fail-closed: unreachable runner fails closed and refuses silent fallback', async () => {
      const prevEnv = process.env.NODE_ENV;
      const prevRunnerUrl = process.env.SKILL_RUNNER_URL;
      const prevSecret = process.env.RUNNER_SHARED_SECRET;

      try {
        process.env.NODE_ENV = 'production';
        process.env.RUNNER_SHARED_SECRET = 'tkxel-vault-internal-runner-secret-key-32b!';
        // Point to a dead/unreachable port
        process.env.SKILL_RUNNER_URL = 'http://127.0.0.1:59999';

        const result = await handlers.handleRunSkill(
          {
            vaultId: vaultLockedId,
            skillName: 'portfolio_stress_test',
          },
          context
        );

        assert.equal(result.isError, true);
        assert.ok(result.content[0].text.includes('Skill Runner service unavailable'));
        assert.ok(result.content[0].text.includes('In-process execution fallback is disabled in production mode'));
      } finally {
        process.env.NODE_ENV = prevEnv;
        process.env.SKILL_RUNNER_URL = prevRunnerUrl;
        if (prevSecret !== undefined) process.env.RUNNER_SHARED_SECRET = prevSecret;
        else delete process.env.RUNNER_SHARED_SECRET;
      }
    });
  } finally {
    // Teardown runner HTTP server
    if (typeof runnerServer.closeAllConnections === 'function') {
      runnerServer.closeAllConnections();
    }
    await new Promise((resolve) => runnerServer.close(resolve));

    // Teardown DB fixtures
    try {
      await db.delete(schema.skills).where(eq(schema.skills.vault_id, vaultLockedId));
      await db.delete(schema.shares).where(eq(schema.shares.vault_id, vaultLockedId));
      await db.delete(schema.vaults).where(eq(schema.vaults.id, vaultLockedId));
    } catch (cleanupErr) {
      console.error('Error during test cleanup:', cleanupErr);
    }
  }
});
